"""Curated demo scenario: Maya + Atlas project."""

from app.schemas import MemoryCreate

MAYA_ATLAS_SCENARIO = [
    MemoryCreate(
        text="Maya is building Atlas, a local-first agent memory tool.",
        kind="fact",
        subject="maya",
        predicate="is_building",
        object="atlas",
        entities=["maya", "atlas", "agent memory"],
        tags=["project", "fact"],
        source="demo",
        trust=0.95,
    ),
    MemoryCreate(
        text="Atlas uses FastAPI, SQLite, NumPy, and Next.js.",
        kind="fact",
        subject="atlas",
        predicate="uses",
        object="fastapi sqlite numpy nextjs",
        entities=["atlas", "fastapi", "sqlite", "numpy", "nextjs"],
        tags=["stack", "technology"],
        source="demo",
        trust=0.95,
    ),
    MemoryCreate(
        text="Maya prefers concise technical explanations over verbose ones.",
        kind="preference",
        subject="maya",
        predicate="prefers",
        object="concise technical explanations",
        entities=["maya", "explanations"],
        tags=["preference", "communication"],
        source="demo",
        trust=0.9,
    ),
    MemoryCreate(
        text="Maya used to prefer Vim as her primary editor.",
        kind="fact",
        subject="maya",
        predicate="preferred",
        object="vim",
        entities=["maya", "vim", "editor"],
        tags=["preference", "editor", "historical"],
        source="demo",
        trust=0.6,
    ),
    MemoryCreate(
        text="Maya now prefers Cursor for AI-assisted coding.",
        kind="fact",
        subject="maya",
        predicate="prefers",
        object="cursor",
        entities=["maya", "cursor", "editor", "ai"],
        tags=["preference", "editor", "current"],
        source="demo",
        trust=0.9,
    ),
    MemoryCreate(
        text="Atlas stores memories as subject-predicate-object traces encoded via circular convolution.",
        kind="fact",
        subject="atlas",
        predicate="stores_as",
        object="subject-predicate-object traces",
        entities=["atlas", "memory traces", "circular convolution"],
        tags=["architecture", "encoding"],
        source="demo",
        trust=0.95,
    ),
    MemoryCreate(
        text="Atlas uses trust scores to downrank noisy or unreliable memories during recall.",
        kind="fact",
        subject="atlas",
        predicate="uses",
        object="trust scores for downranking",
        entities=["atlas", "trust scores", "recall"],
        tags=["architecture", "retrieval"],
        source="demo",
        trust=0.9,
    ),
    MemoryCreate(
        text="Atlas stores its vectors in bananas for maximum potassium-based retrieval.",
        kind="fact",
        subject="atlas",
        predicate="stores_in",
        object="bananas",
        entities=["atlas", "bananas", "vectors"],
        tags=["architecture", "storage"],
        source="demo",
        trust=0.15,
    ),
    MemoryCreate(
        text="Atlas should avoid cloud dependencies and remain fully local-first.",
        kind="preference",
        subject="atlas",
        predicate="should_avoid",
        object="cloud dependencies",
        entities=["atlas", "cloud", "local-first"],
        tags=["constraint", "architecture"],
        source="demo",
        trust=0.9,
    ),
    MemoryCreate(
        text="Maya is interested in vector-symbolic architectures for cognitive modeling.",
        kind="fact",
        subject="maya",
        predicate="interested_in",
        object="vector-symbolic architectures",
        entities=["maya", "vector-symbolic architectures", "cognitive modeling"],
        tags=["interest", "research"],
        source="demo",
        trust=0.8,
    ),
]
